### ISSUE TITLE
Custom icons on mobile (iOS)

### ISSUE THREAD

**Issue by lup3v0** [obsidian-tasks-group/obsidian-tasks-custom-icons#3] opened 2024-01-08 00:12 UTC
Great plugin - thank you!

I am using the [provided css ](https://github.com/replete/obsidian-tasks-custom-icons/blob/main/TasksMonoEmojis-lucide2/TasksMonoEmojis-lucide2.css) and it is working great on desktop (PC and Mac), but not on mobile. 

Any ideas?

Thanks!

**Comment by GGlider** [comment] 2024-01-14 11:13
Thank you so much for this CSS!

I actually have them same issue. I tried to fix it myself, thought maybe it's because the iOS doesn't see the hidden folder. But I didn't manage to solve this.

Another thing which happened lately with a "Tasks" Plugin-Update, that the forward button is not your provided custom view, but the original icon (see screenshot). Again, tried to fix it myself, but did't manage it. :(

<img width="112" alt="Bildschirmfoto 2024-01-14 um 12 13 15" src="https://github.com/replete/obsidian-tasks-custom-icons/assets/153935781/db69776f-65b2-4715-b0d3-474ee659eb97">


Thank you for helping out!

**Comment by replete** [comment] 2024-02-02 15:27
I don't use Obsidian on mobile so haven't tested anything. Welcome PRs though if anyone has a fix

**Comment by GGlider** [comment] 2024-02-13 15:42
Thank you for your reply. The Forward-Button issue is also happening in the regular Obsidian app. Could you have a look on this?

**Comment by replete** [comment] 2024-02-13 16:32
According to https://unicode-org.github.io/emoji/emoji/charts-14.0/emoji-list.html the fast forward icon has a unicode of `U+23E9` so including the relevant SVG file named `u23E9-forward.svg` and running the script again should fix it. I'm not using Tasks anymore but feel free to open a PR with your fix

**Comment by replete** [comment] 2024-05-13 12:04
I tried to fix this on iOS previously, and reverted the changes as it broke things elsewhere.
Safari's WebKit doesn't like something about `unicode-range`.

It's a solvable problem but I no longer use Tasks and I've handed this repo over. If monochrome icons is something you like it may become a part of Tasks at some point if someone develops this solution which is a good foundation.
I've now handed this repo off to `obsidian-tasks-group`

**Comment by replete** [comment] 2024-06-30 12:45
@GGlider The Forward button has been added now, so you can rerun the generator and it will be picked up.

The iOS compatibility fix will come later though

**Comment by replete** [comment] 2024-09-03 19:35
I'll fix this after PR  #14 is merged

**Comment by lup3v0** [comment] 2024-09-15 21:29
Thank you replete for all your efforts! I read your notes carefully, and I was eager to get the emojis working on iOS, but I only had partial success. I ran some tests and here is what I figured out:

- I tested on 2x iOS devices, and strangely, the lucide emojis showed up on one but not the other
- Made sure that both Obsidian installations are based on the latest version 1.6.7 (149), with the latest Task plugin available
- I synced my vault to both phones, so I could be sure that they are using the identical css snippet
- On 16.6.1, with an iPhone 12, the css worked and the emojis are replaced as intended
- On iOS 17.6.1, with an iPhone 11 Pro, the emojis did not render
- I then updated iOS on iPhone 12 to bring also to 17.6.1, and sure enough the emojis stopped working there, too

So, at least for me, there is still something strange going on. Anyone else having the same issue?

**Comment by replete** [comment] 2024-09-15 21:31
@lup3v0 I've an opened pull request at #15 that should resolve the issues, perhaps you could check it out and see if one of the files fixes it for you? It will be merged at some point and become v1.0.6

**Comment by lup3v0** [comment] 2024-09-15 21:45
Hi @replete - I will test anything! I tried using [this css](https://github.com/obsidian-tasks-group/obsidian-tasks-custom-icons/blob/7d131ed8abc620c11fef0c879f88d92b53dd77bd/_vault/.obsidian/snippets/TasksMonoEmojis-lucide.css) but per your description this doesn't have the Safari preferred format of 'u1234'. What am I missing?

**Comment by replete** [comment] 2024-09-15 21:53
Aha, so we do have a problem on modern iOS. Thanks for confirming this, I only had access to iOS 15. 

This appears to be a significant regression bug in Apple Safari in some version after 17. I think using SVG fonts might allow us to get around this issue according to https://forums.macrumors.com/threads/major-text-rendering-bug-in-macos-safari-17-0.2406391/

I'll add a new comment to the PR and when I get a chance generate an SVG version and then if it's okay with you I'll ping you so you can test it.

Thanks for the report.

**Comment by lup3v0** [comment] 2024-09-15 21:57
Yep, will test, just let me know!

**Comment by replete** [comment] 2024-09-15 23:18
I've pushed a potential fix at #15, needs testing but now will serve SVG fonts to Safari on iOS and hopefully remedies the issue.

**Closed** 2024-09-30 09:32 UTC
